drracket/scribblings/tools/tools.scrbl

line 45 changed 'they exports all of the bindings of' to 'they export all of the bindings of'

typo correction line 45 exports to export

---

drracket/scribblings/drracket/interface-essentials.scrbl

The `filter` operates on a list where the style names are translated, but looked for an untranslated name, giving an error when compiling on a system with a French locale, for example ("Moderne" with an "e" instead of "Modern")

Fix "could not find "Modern" style" error when compiling the documentation

---

drracket/scribblings/tools/tools.scrbl

From a confusion on Slack.
Also fixes doc linking to `current-recorded-disappeared-use`

slight clarification of example

---

drracket/scribblings/tools/tools.scrbl

Move the description near the main discussion, instead of in the end,
after the topic has changed to tooltips.
Add the necessary condition that ‘free-identifier=?’ must hold.

Improve description of binding arrows conditions

---

drracket/drracket/HISTORY.txt
drracket/drracket/info.rkt
drracket/drracket/private/syncheck/gui.rkt
drracket/info.rkt

This allows the color scheme package to configure the color of the arrows.

Move syntax-check arrow colors into color scheme.

---

drracket/drracket/private/syncheck/gui.rkt
drracket/scribblings/tools/tools.scrbl

Previously, the example code in the documentation for tooltips did not
work unless there was additional whitespace at the end of the
module. This occurred for two reasons: tooltips outside the valid
range for editor positions were ignored, and tooltips are given in
editor positions, which differ from syntax object positions, so the
tooltip stuck out past the end of the file and was ignored.
This commit does two things to fix this:
1. Tooltip regions are truncated, rather than ignored, when they
exceed the file length.
2. The docs mention the difference in indexing, and the sample code
contains the necessary sub1 calls.
This solution is backwards-compatible - some non-working programs now
work, but working programs won't change the semantics of tooltip
placement.
Fixes #113.

Display tooltips that are too large, and update docs on positions

---

drracket/scribblings/drracket/extending.scrbl

This documents the change in racket/htdp#55.

Add document for extending help search context

---

drracket-test/tests/drracket/syncheck-test.rkt
drracket-tool-lib/drracket/private/syncheck/traversals.rkt

Fixes #267.
Due to the need to define macros in these tests, the test cases are rather noisy. I don’t know if that is considered a problem or not, but if it is, I can look into what it would take to adjust the test harness so that the macro can be defined in a separate file, so only the macro uses are seen by Check Syntax.

syncheck: Look at 'sub-range-binders properties on disappeared ids

---

drracket/drracket/private/rep.rkt
drracket/info.rkt

The message is "memory limit".  Reuse the limit-memory-limited constant which seems fine
The construction of the message is suboptimal but should be fine for now
Signed-off-by: Alexander Shopov <ash@kambanaria.org>

Translate a message on the startup screen

---

drracket/scribblings/drracket/interface-essentials.scrbl

Used to be three supplied; now rather more, so reword a little more vaguely.

drracket/interface-essentials.scrbl: fix out of date number of color schemes

---

drracket/drracket/private/stack-checkpoint.rkt

The `#f` frames are already dropped in `cut-stack-at-checkpoint`, causing
this test to fail on Racket CS which has some extra `#f` frames at the
beginning.
Also, make tests more informative.

Drop `#f` frames in stack checkpoint test.

---

drracket/drracket/private/debug.rkt
drracket/drracket/private/rep.rkt
drracket/drracket/private/stack-checkpoint.rkt

Commit 4b3cff1abfa69 changed (perhaps unintentionally) the contract
for `error-display-handler/stacktrace`. The previous documented
contract expected `(or/c #f list?)` but the new code expects a
`viewable-stack?`.
This changes the two clients in this repository, but there might
be others elsewhere.
`tests/drracket/synchek-test`, which was broken by the change,
passes after this commit.

Repair `drracket:debug:error-display-handler/stacktrace`.

---

.github/workflows/ci.yml

Only runs syncheck-test to start, for testing.
cc #362

Add GHA CI on pull-requests and commit.

---

drracket/scribble/tools/drracket-buttons.rkt

Rather than send-url/file on Windows, use start, taking care to supply an
empty first argument (which Windows interprets as a window title).
Use this for HTML too. In fact, xdg-open on GNU/Linux etc., open on macOS,
and start on Windows all work with both files and URLs, so this would work
for http URLs too etc.
Use system* rather than system to avoid quoting problems.

scribble: make Scribble PDF button work on 'unix, and simplify for HTML

---

drracket/scribblings/tools/language.scrbl
drracket/scribblings/tools/rep.scrbl

Remove `#:mode override` for methods that are defined with `define/public`.
Change `augment` to `pubment` for `after-many-evals`

Partially fixes racket/gui#185

---

drracket-test/tests/drracket/syncheck-test.rkt
drracket/drracket/private/syncheck/gui.rkt

Renaming in DrRacket is currently broken in two ways.
1. Consider the program:
#lang racket
(require racket/list)
Right clicking `require` will offer users to rename the `racket`
identifier which doesn't make much sense. Users right click `require`
because they want to rename that particular identifier, not others.
<s>
2. To continue from the above example, renaming `racket` to
`racket/base` will cause all identifiers imported from `racket` to be
renamed to `racket/base`. That is, it would result in:
#lang racket/base
(require/base racket/list)
This bug will become even more annoying after racket/racket#3391
is merged, since renaming any defined identifier will cause
`all-defined-out` to be renamed as well.
</s>
This PR fixes both issues. That is, renaming at a position will pick an …

Fix renaming in DrRacket

---

.github/workflows/ci.yml

Currently the CS variant fails with `##[error]Unexpected HTTP response: 404`. This PR fixes the problem. See also the discussion at https://github.com/racket/drracket/pull/412 and https://github.com/Bogdanp/setup-racket/pull/12.

Bump version of setup-racket to 0.10

---

drracket-tool-doc/scribblings/drracket-tools/drracket-tools.scrbl

The symbol has always been module-lang instead of module-lang-require.
It's simply documented incorrectly.

doc: module-lang-require -> module-lang

---

drracket/drracket/private/named-undefined.rkt

Add contract to defensive code. Found automatically by defensive-to-contract package.

Adding contract to defensive code

---

drracket-test/tests/drracket/test-engine-test.rkt

The test-engine rewrite zapped a few spaces; follow that change.

Unbreak test-engine-test.

---

drracket-tool-doc/scribblings/drracket-tools/drracket-tools.scrbl
drracket-tool-lib/drracket/check-syntax.rkt
drracket-tool-lib/drracket/private/syncheck/traversals.rkt
drracket-tool-test/tests/check-syntax/syncheck-direct.rkt

The current requirement of path in make-traversal is that it is
either #f or a path-string? However, because we parameterize
current-load-relative-directory to be this path, providing
any non complete-path? will result in a contract error.
This PR thus strengthens the requirement so that the provided path
must be complete-path?
The PR also fixes the show-content procedure so that
it satisfies the contract. Note that we need additional
parameterization of current-load-relative-directory so that
macro expansion can work correctly on relative path source like:
```
;; main.rkt
(require drracket/check-syntax)
(show-content "test/a.rkt")
;; test/a.rkt
(require "b.rkt")
;; test/b.rkt
1
```
Also cleanup description about `add-id-set`, since the method is no longer called.

add relative path support to make-traversals

---

.github/workflows/ci.yml

Without `-a`, multiple runs of `xvfb-run` will use the same server number. If the first `xvfb-run` has not freed the resource yet by the time the second `xvfb-run` is invoked, a conflict will occur, causing an error.
With `-a`, the second `xvfb-run` will automatically pick a different server number, thus avoiding the conflict.
CC: @samth

CI: use automatic server numbering

---

drracket/drracket/private/module-language-tools.rkt

Either of drscheme:opt-out-toolbar-buttons /
drracket:opt-out-toolbar-buttons can be used to turn off the opt-out
buttons.  The way it was implemented, you needed both.  Unbreak.

Handle drscheme:opt-out-toolbar-buttons correctly

---

drracket/drracket/private/debug.rkt
drracket/drracket/private/stack-checkpoint.rkt

Backtrace display mutates viewable stacks. Therefore, we should copy
them first so that subsequent activations still produce correct result.
Fixes #461

backtrace: fix empty backtrace on subsequent activation

---

drracket/drracket/private/debug.rkt

Also adjust srcloc display to be consistent with
how it's usually displayed.
Fixes #463

backtrace: fix font size inconsistency

---

drracket-test/tests/drracket/test-engine-test.rkt

This accounts for upcoming layout tweaks, which omit spurious
newlines - zap a relevant newline from a regexp.

Make test-engine-test a tiny bit more lenient.

---

drracket-test/tests/drracket/test-engine-test.rkt

This PR adds a minimum test related to racket/htdp#135 and racket/htdp#143 for the test engine. It check that a failing `check-expect` involving images should generate a non-textual output.

Add an image test for the test engine.

---

drracket/drracket/private/in-irl-namespace.rkt
drracket/drracket/private/insulated-read-language.rkt
drracket/drracket/private/module-language-tools.rkt
drracket/info.rkt
drracket/scribblings/tools/lang-tools.scrbl

For languages where there's not a single way to indent --- especially
where indentation can drive parsing instead of always the other way
around --- the indent operation might cycle through some
possibilities. In that case, multi-line indentation by indenting each
line separately does not work well. The 'drracket:range-indentation
configuration hook lets a language implement multi-line indentation
differently.

add 'drracket:range-indentation for #lang-controlled block indentation

---

drracket/drracket/private/debug.rkt
drracket/drracket/private/eval.rkt
drracket/info.rkt

This way, users of simple-tree-text-markup/port can generate links to
srclocs represented by the note% snips.
This goes back to a discussion @rfindler and I have had. Should be viewed as a first draft.

Have note% implement srcloc-special<%>.

---

drracket/drracket/private/tooltip.rkt

Found by [running tests against changes](https://github.com/racket/rackunit/pull/153) that enable syntax location for typed rackunit:
```
2022-01-20T16:41:00.3310133Z raco setup: --- summary of errors ---                              [16:41:00]
2022-01-20T16:41:00.3311127Z raco setup:   /github/home/racketdist-current-CS/share/pkgs/drracket/drracket/private/tooltip.rkt:221:2: Type Checker: Macro check-equal? from typed module used in untyped code
2022-01-20T16:41:00.3311894Z raco setup:     in: (check-equal? (strings->strings+spacers (quote ())) (quote ()))
2022-01-20T16:41:00.3312711Z raco setup:     compiling: <pkgs>/drracket/drracket/private/tooltip.rkt
2022-01-20T16:41:00.3319483Z raco pkg install: packages installed, although setup reported errors
2022-01-20T16:41:00.3880671Z …
```

use the regular rackunit

---

drracket/scribblings/tools/lang-tools.scrbl

Strengthen contract.
Fix some region comment examples.
As pointed out by @rfindler on #634.

Fix docs for drracket:comment-delimiters

---

drracket/scribblings/drracket/menus.scrbl

replace command.com reference to `cmd.exe` using terminology from Microsoft documentation 
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands 
nb command.com was last present in Windows ME.

Update menus.scrbl to cmd.exe

---

drracket/drracket/private/syncheck/online-comp.rkt
drracket/scribblings/tools/tools.scrbl

discard them unless their source matches the file that originally triggered the expansion
The goal here is to avoid showing annotations from files that are required (and expanded as part of that process).
related to racket/racket#4811

when receiving syntax objects from 'online-check-syntax logger,

---

drracket/scribblings/tools/lang-tools.scrbl

This is a follow-up of cb6a7e88308d4f1f69b

doc: linkify + fix incorrectly closed bracket + typo

---

drracket/drracket/private/unit.rkt

Prior this PR, the language name in the language selection dropdown could read "Determine language from source custom" with some combinations of settings, which doesn't make sense. Either "custom" should be removed entirely,
or it should be parenthesized. Here, I use brackets to make it similar to the language name shown in the REPL pane.

Surround "custom" with brackets in the language selection dropdown

---

.github/workflows/resyntax-autofixer.yml

The autofixer currently runs on a random file. However, if that file has nothing to fix, no changes are made so nothing happens. This pull request changes Resyntax to analyze the entire repository but uses the `--max-fixes` flag to limit the number of changes made to no more than ten fixes. Additionally, `xvfb-run` is removed since Resyntax no longer depends on the GUI framework.

Fix the Resyntax autofixer

---

.github/workflows/resyntax-autofixer.yml

I added the `--output-as-commit-message` flag to Resyntax which lets it output its summary as a Github markdown commit message. The results look like [this](https://github.com/jackfirth/racket-disposable/pull/123).

Use new Resyntax autofixer commit message format

---

drracket-test/tests/drracket/language-test.rkt
drracket-test/tests/drracket/module-lang-test.rkt
drracket-test/tests/drracket/private/drracket-test-util.rkt
drracket-test/tests/drracket/private/module-lang-test-utils.rkt

This PR adds some tests for racket/htdp#228, racket/htdp#229 and racket/htdp#230.

Adds some tests for racket/htdp#228, racket/htdp#229 and racket/htdp#230

---

drracket/drracket/private/unit.rkt

When given symbols, they could be names for unsaved buffers. Directly match the definition window and the interaction window instead. Otherwise, fallback to `find-matching-tab` for `path-strings?` like before.
Related to racket/drracket@d27a4804ab8c252afb06ce94ef77057bdac1d661.

`make-visible`: use `port-name-matches?` for symbols

---

drracket/scribblings/drracket/keybindings.scrbl

Change the keybindings page to use the platform independent notation as is present in the 'Show Active Keybindings' keybindings window.

Align keybindings doc with DrR UI

---

drracket-core-lib/drracket/private/in-irl-namespace.rkt
drracket-core-lib/drracket/private/insulated-read-language.rkt
drracket-core-lib/drracket/private/module-language-tools.rkt
drracket-core-lib/info.rkt
drracket-core/info.rkt
drracket-core/scribblings/tools/lang-tools.scrbl
drracket/info.rkt

For a language that can offer indentation alternatives, such as Rhombus, allow a reserve-order request via a new argument to a function provided for `drracket:indentation` and `drracket:range-indentation`.
The new argument is a list of options, just in case additional options are needed in the future. Currently, the list is always `'()` or `'(reverse)`.

add support for reverse-order cycling in `drracket:indentation` and `drracket:range-indentation`
